version: '3.3'
services:

    db_connector:
      image: mcquiggan/db_connector:latest
      build:
        context: ./db_connector
        dockerfile: Dockerfile
      ports:
      - "5000:5000"
      depends_on:
        - mongo

    mongo:
      container_name: mongo
      image: mongo
      ports:
      - "27017:27017"